version: '3.8'

services:
  db:
    image: postgres:15.2
    container_name: db
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  bot:
    container_name: bot
    build: .
